version: '3.4'

volumes:
  redis-data: null
services:
  neo4j:
    image: 'bitnami/neo4j:latest'
    ports:
        - '7474:7474'
        - '7473:7473'
        - '7687:7687'
    environment:
        - NEO4J_PASSWORD=password

  redis:
    image: 'redis:alpine'
    ports:
        - '6379:6379'
    command:
      - redis-server
      - '--appendonly'
      - 'yes'
    volumes:
      - 'redis-data:/data'

  redis-commander:
      hostname: redis-commander
      image: 'rediscommander/redis-commander:latest'
      restart: always
      environment:
          - 'REDIS_HOSTS=local:redis:6379'
      ports:
          - '6380:8081'

  rq-dashboard:
      image: jaredv/rq-docker:0.0.2
      command: rq-dashboard -H redis
      ports:
          - 9181:9181
